# 1. Server Configuration
# This is the port where our "waiter" (API) will listen for orders
server.port=8080

# 2. MongoDB Database Configuration
# This is the exact map to our "pantry"
spring.data.mongodb.uri=mongodb://localhost:27017/student_marks_db